import "./globals.css";
import { Inter } from "next/font/google";

import Followbar from "@/components/layout/Followbar";
import Sidebar from "@/components/layout/Sidebar";
import LoginModal from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/RegisterModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto xl:px-30 max-w-6xl">
          <div className="grid grid-cols-4 h-full">
            <Sidebar />
			
            <RegisterModal />
            <LoginModal />
            <div
              className="col-span-3 lg:col-span-2"
              style={{ borderColor: "rgb(239, 243, 244)" }}>
              {children}
            </div>

            <Followbar />
          </div>
        </div>
      </body>
    </html>
  );
}
