"use client";

import "./globals.css";
import { Inter } from "next/font/google";

import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";

import Followbar from "@/components/layout/Followbar";
import Sidebar from "@/components/layout/Sidebar";
import LoginModal from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/RegisterModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto xl:px-30 max-w-6xl">
          <div className="grid grid-cols-4 h-full">
            <SessionProvider>
              <Sidebar />
              <Toaster />
              <RegisterModal />
              <LoginModal />
              <div
                className="col-span-3 lg:col-span-2"
                style={{ borderColor: "rgb(239, 243, 244)" }}
              >
                {children}
              </div>

              <Followbar />
            </SessionProvider>
          </div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
